# Change these first
owner: ByKaj # Your GitHub organization or username, where this repository lives
repo: Fortifymail-Status # The name of this repository

sites:
  - name: Dashboard
    url: https://app.fortifymail.com
    maxResponseTime: 5000
  - name: Website
    url: https://www.fortifymail.com
    maxResponseTime: 5000
  - name: Inbound mail
    icon: https://raw.githubusercontent.com/ByKaj/Fortifymail-Status/master/assets/favicon.ico
    check: "tcp-ping"
    url: mail.fortifymail.com
    port: 25
    maxResponseTime: 5000
  - name: Outbound mail
    icon: https://d1idiovbex4hy4.cloudfront.net/icon/f2b32bda85a5a4a613eb47fb01c57ce3-2b4a0b6e3c7d785e7e0d22f5d540dce9.svg
    check: "tcp-ping"
    url: email-smtp.eu-central-1.amazonaws.com
    port: 587
    maxResponseTime: 5000
  - name: API
    url: https://app.fortifymail.com/api/notifications?page=0
    headers:
      - "Authentication: $FM_API_KEY"
    maxResponseTime: 5000

assignees: # Users to assign downtime issues (optional)
  - ByKaj

status-website:
  cname: status.fortifymail.com
  logoUrl: https://raw.githubusercontent.com/ByKaj/Fortifymail-Status/master/assets/icon.svg
  faviconSvg: https://raw.githubusercontent.com/ByKaj/Fortifymail-Status/master/assets/icon.svg
  name: Fortifymail
  #theme: light
  #themeUrl: https://raw.githubusercontent.com/ByKaj/Fortifymail-Status/master/assets/default.css
  css: "body { background-color: #f8f9fa } footer { font-size: 0.8em; }"
  introTitle: "**Fortifymail** Service Status"
  introMessage: Status, availability and response time of the Fortifymail web and email services. The **Mobile App** and the **Browser Extension** are dependent on the availability of the API.
  navbar:
    - title: Home
      href: https://www.fortifymail.com
    - title: Dashboard
      href: https://app.fortifymail.com
    - title: Status
      href: /

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org).<br>&copy; 2023 [Cetana Solutions](https://www.cetana.nl). All rights reserved.
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
