# Change these first
owner: ByKaj # Your GitHub organization or username, where this repository lives
repo: Fortifymail-Status # The name of this repository

sites:
  - name: Dashboard
    url: https://app.fortifymail.com
  - name: Website
    url: https://www.fortifymail.com
  - name: Inbound mail service
    check: "tcp-ping"
    url: mail.fortifymail.com
    port: 25
  - name: Outbound mail service
    check: "tcp-ping"
    url: email-smtp.eu-central-1.amazonaws.com
    port: 587
assignees: # Users to assign downtime issues (optional)
  - ByKaj
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aliasshield.com
  # baseUrl: /Fortifymail-Status
  logoUrl: https://raw.githubusercontent.com/ByKaj/Fortifymail-Status/master/assets/icon.svg
  name: Fortifymail
  introTitle: "**Fortifymail** Service Status"
  introMessage: Uptime and status page for the Fortifymail web and email services.
  navbar:
    - title: Home
      href: https://www.fortifymail.com
    - title: Dashboard
      href: https://app.fortifymail.com
    - title: Status
      href: /
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
